config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controller: {omniauth_callbacks: "omniauth_callbacks"}
  resources :product_types
  root 'home#index'

  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :product_type
    serialize :properties, Hash
    
    validate :validate_properties
    
    def validate_properties
        product_type.fields.each do | field |
            if field.required? && properties[field.name].blank?
                errors.add field.name, "must not be blank."
            end
        end
    end
end

app/models/product_field.rb
class ProductField < ActiveRecord::Base
  belongs_to :product_type
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
    has_many :fields, class_name: "ProductField"
    accepts_nested_attributes_for :fields, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates_presence_of :user_name
  validates_uniqueness_of :user_name
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_ot_create do | user |
      user.provider = auth.provider
      user.uid = auth.id
      user.username = auth.info.nickname
    end
  end
  
  def self.new_with_session(params, session)
      if session["devise.user_attributes"]
        new(session["devise.user_attributes"], without_protection: true) do | user |
          user.attributes = params
          user.valid?
        end
      else
        super
      end
  end
  
  def password_required?
    super && provider.blank?
  end
  
  def update_with_password(params, *option)
    if encrypted_password.blank?
      update_attributes(params, *option)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callback_controller.rb
class OmniauthCallbackController < ApplicationController
    def all
        #raise request.env["omniauth.auth"].yaml
        user = User.from_omniauth(request.env["omniauth.auth"])
        if user.persisted?
            flash[:success] = "Signed In"
            sign_in_and_redirect user
        else
            session["devise.user_attributes"] = user.attributes
            redirect_to new_user_registration_url
        end
    end
    
    alias_method :twitter, :all
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]

  # GET /product_types
  # GET /product_types.json
  def index
    @product_types = ProductType.all
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show
  end

  # GET /product_types/new
  def new
    @product_type = ProductType.new
    #@product_type.fields.build
  end

  # GET /product_types/1/edit
  def edit
  end

  # POST /product_types
  # POST /product_types.json
  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: 'Product type was successfully created.' }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1
  # PATCH/PUT /product_types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to @product_type, notice: 'Product type was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    @product_type.destroy
    respond_to do |format|
      format.html { redirect_to product_types_url, notice: 'Product type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_type_params
      params.require(:product_type).permit(:name, fields_attributes: [:id, :name, :field_type, :required, :product_type_id])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new(product_type_id: params[:product_type_id])
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :product_type_id, properties: [:id, :author, :page_count, :paperback])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def link_to_add_fields(name, f, association)
        new_object = f.object.send(association).klass.new
        id= new_object.object_id
        fields=f.fields_for(association, new_object, child_index: id) do | builder |
            render(association.to_s.singularize + "_fields", f: builder)
        end
        link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callback_helper.rb
module OmniauthCallbackHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<div class="jumbotron text-center">
  <h1>MyWorkShop is coming soon..</h1>
  <p>Thanks for patience!</p>
</div>
  
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>ROR Tutorials</h3>
      <p>Coming Soon...</p>
    </div>
    <div class="col-sm-4">
      <h3>My App</h3>
      <p>Coming Soon...</p>
    </div>
    <div class="col-sm-4">
      <h3>Q/A</h3>
      <p>Coming Soon...</p>
    </div>
  </div>
</div>

app/views/layouts/_application.html.erb
<% if !flash[:notice].blank? %>
  <div id='flash'>
    <%= render partial: 'layouts/flash_notice',locals: {notice: flash[:notice]} %>
  </div>
<% end %>
<% if !flash[:alert].blank? %>
  <div class="alert alert-warning fade in">
    <span class="fa fa-bell-o"></span>
    <a href="#" class="close" data-dismiss="alert">&times;</a>  
    <%= flash[:alert] %>
  </div>
<% end %>
<% if flash[:notice].blank? and flash[:alert].blank? %>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <span class="fa fa-bell-o"></span>
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      <%= value %>
    </div>
  <% end %>
<% end %>

  <%= yield %>

app/views/layouts/_navigation.html.erb
<nav class = "navbar navbar-default" role = "navigation">
   <div class = "navbar-header">
      <button type = "button" class = "navbar-toggle" 
         data-toggle = "collapse" data-target = "#example-navbar-collapse">
         <span class = "sr-only">Toggle navigation</span>
         <span class = "icon-bar"></span>
         <span class = "icon-bar"></span>
         <span class = "icon-bar"></span>
      </button>
		
      <%= link_to("MyWorkShop", root_path, :class => "navbar-brand") %>
   </div>
   
   <div class = "collapse navbar-collapse" id = "example-navbar-collapse">
	
      <ul class = "nav navbar-nav">
         <li class="">
            <%= link_to "Admin", product_types_path %> 
          </li>
          <li class="">
            <%= link_to "Dynamic Form", products_path %>
          </li>
          <li class="">
            <%= link_to "Nested Models", products_path %>
          </li>
          <li class="">
            <%= link_to "Others", products_path %>
          </li>
          <li class="dropdown">
            <a href = "#" class = "dropdown-toggle" data-toggle = "dropdown">
               My Blogs
               <b class = "caret"></b>
            </a>
            
            <ul class = "dropdown-menu">
               <li><%= link_to "Box With ROR OAuth ", "http://qiita.com/alokrawat050/items/3028c89b9e449a6f614e", :target => "_blank" %></li>
               <li class = "divider"></li>
               <li><a href = "#">Coming Soon</a></li>
            </ul>
          </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                Logged in as <strong><%= current_user.email %></strong>.
                <li><%= link_to 'Edit Profile', edit_user_registration_path %> </li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              <% else %>  
                <li><%= link_to 'Sign Up', new_user_registration_path %> </li>
                <li><%= link_to 'LogIn', new_user_session_path %></li>
              <% end %>
          </ul>
   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Language" content="ja">
    <title>MyWorkShop | <%= content_for?(:title) ? yield(:title) : "MyWorkShop" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>    
  </head>
  
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="container">
      <div class="row">
        <%= render partial: '/layouts/navigation' %>
        <%= render partial: '/layouts/application' %>
      </div>
    </div>
  </body>
</html>
     

app/views/product_types/_field_fields.html.erb
<fieldset>
    <%= f.select :field_type, %w[text_field check_box] %>
    <%= f.text_field :name, placeholder: "field_name" %>
    <%= f.check_box :required %><%= f.label :required %>
    <%= f.hidden_field :_destroy %>
    <%= link_to '[remove]', '#', class: "remove_fields" %>
</fieldset>

app/views/product_types/_form.html.erb
<%= form_for(@product_type) do |f| %>
  <% if @product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
      <% @product_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <%= f.fields_for :fields do |builder| %>
    <%= render 'field_fields', f: builder %>
  <% end %>  
  <%= link_to_add_fields "Add Field", f, :fields %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_types/edit.html.erb
<h1>Editing Product Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_type %> |
<%= link_to 'Back', product_types_path %>

app/views/product_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Product Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_types.each do |product_type| %>
      <tr>
        <td><%= product_type.name %></td>
        <td><%= link_to 'Show', product_type %></td>
        <td><%= link_to 'Edit', edit_product_type_path(product_type) %></td>
        <td><%= link_to 'Destroy', product_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product type', new_product_type_path %>

app/views/product_types/new.html.erb
<h1>New Product Type</h1>

<%= render 'form' %>

<%= link_to 'Back', product_types_path %>

app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_type.name %>
</p>

<%= link_to 'Edit', edit_product_type_path(@product_type) %> |
<%= link_to 'Back', product_types_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.hidden_field :product_type_id %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  
  <%= f.fields_for :properties, OpenStruct.new(@product.properties) do | builder | %>
    <% @product.product_type.fields.each do | field | %>
      <%= render "products/fields/#{field.field_type}", field: field, f: builder %>
    <% end %>
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/fields/_check_box.html.erb
<div class="field">
    <%= f.check_box field.name %>
    <%= f.label field.name %>
</div>

app/views/products/fields/_text_field.html.erb
<div class="field">
    <%= f.label field.name %>
    <%= f.text_field field.name %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= form_tag new_product_path, method: :get do %>
  <%= select_tag :product_type_id, options_from_collection_for_select(ProductType.all, :id, :name) %>
  <%= submit_tag "New Product", name: nil %>
<% end %>

<%#= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price, :locale => :ja) %>
</p>

<% @product.properties.each do |name, value| %>
  <p>
    <b><%= name.humanize %>:</b>
    <%= value %>
  </p>
<% end %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>